package com.example.im_chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.im_chat.entity.ChatMessage;
import com.example.im_chat.entity.DialogMessage;

import com.example.im_chat.db.ChatMessageDao;
import com.example.im_chat.db.DialogMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig dialogMessageDaoConfig;

    private final ChatMessageDao chatMessageDao;
    private final DialogMessageDao dialogMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        dialogMessageDaoConfig = daoConfigMap.get(DialogMessageDao.class).clone();
        dialogMessageDaoConfig.initIdentityScope(type);

        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);
        dialogMessageDao = new DialogMessageDao(dialogMessageDaoConfig, this);

        registerDao(ChatMessage.class, chatMessageDao);
        registerDao(DialogMessage.class, dialogMessageDao);
    }
    
    public void clear() {
        chatMessageDaoConfig.clearIdentityScope();
        dialogMessageDaoConfig.clearIdentityScope();
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public DialogMessageDao getDialogMessageDao() {
        return dialogMessageDao;
    }

}
